### ISSUE TITLE
I cant access the duration variable from anywhere else!

### ISSUE THREAD

**Issue by AaronGillBraun** [ddsol/mp3-duration#4]
I cant access the "duration" var from anywhere else. I tried appending it to an array, making it global but i just get "undefined"

**Comment by ddsol** [comment]
You probably get undefined because you're trying to access it before it's done calculating. If you pepper your code with `console.log` statements you'll probably find the displaying of the result to come before the storing of the result, or in other words, before the result is available.

To illustrate:
```javascript
var mp3Duration = require('mp3-duration');

var duration; //<-- global or module-global variable

mp3Duration('file.mp3', function (err, _duration) {
  if (err) return console.log(err.message);
  duration = _duration;
  console.log('Your file is ' + duration + ' seconds long');
  //Code that needs duration should really go right here or should get called here
  //doSomethingWithDuration(_duration);
});
console.log('Duration is now:', duration); //<-- logs undefined
setTimeout(function(){
  console.log('The duration from elsewhere:', duration);
}, 10000);
```

That makes it available. The var `duration` is now global (or at least module-global).
Unfortunately, if you try to access it elsewhere then how would you know when? Because `mp3Duration` is an asynchronous function, it takes a bit before it calls back with the result. In the meantime, the code after the `mp3Duration` call just keeps running. The `duration` var remains undefined.

So the above code would show:
```
(mp3Duration starting the process of calculating the length here)
Duration is now: undefined
(length is calculated now and callback is called)
Your file is 12.7 seconds long
(wait 10 seconds)
The duration from elsewhere: 12.7
```

The `setTimeout` is only to demonstrate that it is indeed available from elsewhere, but this is really not the way to do it.

I did a google and [here](http://www.informit.com/articles/article.aspx?p=2265406)'s [more info](https://www.google.com/search?q=node+js+asynchronous+programming).

**Comment by AaronGillBraun** [comment]
Thank you for your quick and helpful reply
