### ISSUE TITLE
Unable to retrieve external assets

### ISSUE THREAD

**Issue by EricNetsch** [ddsol/mp3-duration#7]
I was unable to get this working with any external assets. Please let me know if this is possible or what the issue might be. The error is : 
"ENOENT: no such file or directory, open 'http://www.mfiles.co.uk/mp3-downloads/purcell-funeral-music-for-queen-mary.mp3'"

```
mp3Duration('http://www.mfiles.co.uk/mp3-downloads/purcell-funeral-music-for-queen-mary.mp3', function (err, duration) {
  if (err) return console.log(err.message);
  console.log('Your file is ' + duration + ' seconds long');
});
```

**Comment by ddsol** [comment]
Yes, it takes a file name. So no go on the url thingy because that's not a file which is why the error "no such file".

You can download it and then save it as a local file or even remote file. You can then pass the name of the file and voila it will work.

Note that straight up converting it to allow urls is painful because it does seeking and that is not easy on an http stream.
